### ISSUE TITLE
Question: Output possible?

### ISSUE THREAD

**Issue by nvanderperren** [timothyryanwalsh/brunnhilde#40] opened 2019-02-07 10:52 UTC
I'm scanning a folder of 85 GB with Brunnhilde. It would be interesting to get some output of what's Brunnhilde doing. Now it's sometimes not clear if the software froze or is still doing something. I can follow it a bit by checking if the size of the `siegfried.csv` has grown, but sometimes it takes a very long time before that size changes, making it look like the software is stuck. 

edit: or maybe I'm not seeing anything in the terminal because I'm using Brunnhilde GUI.

**Comment by EagleRock1313** [comment] 2019-02-07 15:19
Hi nvanderperren,

I have had the same issue.  I installed nmon to monitor the read write activity of the disk(and many other things), to make sure the program is still working.  It is pretty powerful, and takes a bit of time to google around and read how others are using it.  A link to the Wikipedia entry and website is here:

https://en.wikipedia.org/wiki/Nmon

Best Regards,
Sandy

**Comment by timothyryanwalsh** [comment] 2019-02-08 18:34
Hi @nvanderperren. Thanks for filing this issue! This feature is definitely high on my development to-do list for future versions of Brunnhilde, along with improvements to error reporting, handling of multi-partition disk images, and Windows support and a general cleanup/refactor of the codebase. Other projects have prevented me from putting much time into Brunnhilde lately but I'm hoping to give a first crack at Brunnhilde 2.0 this summer.

In the meantime, I do see one potential stop-gap "fix". Siegfried has an option to log current progress and time to the terminal (`sf -log p,t DIR > OUTPUT.yaml`). In practice, this means Siegfried will stream a continually updated list of the files it is currently scanning. This makes it much easier to verify that Siegfried is still working as intended and not hung up or errored. I could add a new flag to Brunnhilde that would enable this setting in Siegfried. This should help, as the Siegfried scan tends to be the longest and most opaque process Brunnhilde runs. The downside I can see is that for a large scan this would mean that a very large amount of information is logged to the terminal, but if this functionality is optional and turned off by default that might be okay.

What do you think?

**Comment by nvanderperren** [comment] 2019-02-09 13:25
That's a good fix for me! Thanks for your answer.

**Comment by timothyryanwalsh** [comment] 2019-02-09 18:38
Okay, I just pushed out a 1.8.1 release with this patch! Try upgrading on your machine with:

`pip install --upgrade brunnhilde`

Closing this issue but feel free to leave any comments or re-open if you run into unexpected behavior!

**Comment by timothyryanwalsh** [comment] 2019-02-09 18:39
(I should add, the patch adds a `-v` or `--verbosesf` argument which will enable the verbose Siegfried logging to the terminal)

**Closed by timothyryanwalsh** 2019-02-09 18:38 UTC
