### ISSUE TITLE
_csv.Error: field larger than field limit (131072)

### ISSUE THREAD

**Issue by MSavels** [timothyryanwalsh/brunnhilde#35] opened 2018-05-09 14:19 UTC
![brunnhilde_error](https://user-images.githubusercontent.com/27803645/39819315-6b609bda-53a3-11e8-82aa-8c5654022242.png)
Hi,

The attached screeshot shows an error I'm getting with one particular directory. I guess the error is caused by one or more files that have very long paths. When the CSV-report is written, the field size is apparently longer than the csv.field_size_limit of 131072, which causes the csv-library to throw "_csv.Error: field larger than field limit (131072)". One workaround would be to allow this limit to be larger in special cases (see: [https://stackoverflow.com/questions/15063936/csv-error-field-larger-than-field-limit-131072]). It would be convenient if a longer field length could be passed as an argument to Brunnhilde or maybe there's another workaround.

Kind regards,

Maarten

**Comment by timothyryanwalsh** [comment] 2018-05-09 20:34
Hi Maarten. Thank you for the bug report and the helpful link! I will investigate in the next few days and get back to you. I have one other outstanding bug related to unicode handling of file names and so it seems like a good time for a bugfix update.

**Comment by timothyryanwalsh** [comment] 2018-06-07 19:38
Hi @MSavels - my apologies for the delay, I'm now looking into this issue. The error appears to be when the Siegfried-written CSV file is read into the sqlite3 database. I think your field_size_limit should work, but I'm wondering what the cause of the long field size is. Would you be willing to share the offending CSV file so I can investigate?

**Comment by richardlehane** [comment] 2018-06-18 06:15
It'd have to be a really long path surely :) My bet is that it will be the basis field. Sometimes sf goes a bit beserk and records a huge amount of data in this field. It's been reported as an issue here: https://github.com/richardlehane/siegfried/issues/111
I've developed a fix for this which will be in the 1.7.9 release that should land about the end of this month. Suspect that fix will resolve this issue too

**Comment by timothyryanwalsh** [comment] 2018-06-18 16:42
Thanks, @richardlehane! I'll keep this issue open for now. @MSavels - would you mind testing this again with Siegfried 1.7.9 when it's released and letting me know if you're still experiencing the issue?

**Comment by MSavels** [comment] 2018-06-19 07:51
Hi,
Sorry for not answering earlier. I was away on holidays. I can't share the offending CSV-file, as it is never written. After the error, Brunnhilde just exits. What I can do, however, is test again only with Siegfried and see if the same error pops up. Naturally, I'll test again with Siegfried 1.7.9.
Regards,
Maarten

**Comment by MSavels** [comment] 2018-08-01 11:51
Hi,
I redid the analysis of the offending dataset only with Siegfried 1.7.8. Now the CSV-file is written and opens without problems. I can send you the CSV-file, it's about 80 MB.

Regards,
Maarten

**Comment by timothyryanwalsh** [comment] 2018-08-31 17:40
Hi Maarten. Since the Siegfried update solved this problem, I'm marking this issue as closed. Thanks for reporting!

**Closed by timothyryanwalsh** 2018-08-31 17:40 UTC
